version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "d0ck3rX12!4354"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"